import { Camera, Plane, Quaternion, Raycaster, Spherical, Vector2, Vector3, WebGLRenderer } from 'three';
export declare class MapControls {
    private camera;
    private renderer;
    private plane;
    target: Vector3;
    bounds: {
        top: number;
        left: number;
    };
    touch: boolean;
    mousePosition: Vector2;
    mouseCast: Vector3;
    raycaster: Raycaster;
    panning: boolean;
    panStart: Vector3;
    panOffset: Vector3;
    zooming: boolean;
    zoomStart: Vector2;
    zoomOffset: Vector2;
    minZoom: number;
    maxZoom: number;
    zoomScale: number;
    touchZoomScale: number;
    rotating: boolean;
    rotateStart: Spherical;
    rotateMouseStart: Vector2;
    rotateOffset: Vector2;
    maxPhi: number;
    minPhi: number;
    quat: Quaternion;
    spherical: Spherical;
    offset: Vector3;
    constructor(camera: Camera, renderer: WebGLRenderer, plane: Plane);
    onChange(): void;
    private onMouseMove;
    private onMouseDown;
    private onMouseUp;
    private onTouchDown;
    private onTouchMove;
    private onTouchUp;
    private setMousePosition(x, y);
    private onWheel;
    private animate;
    private update();
    private startPan();
    private stopPan();
    private startZoom();
    private stopZoom();
    private zoomIn(e);
    private zoomOut(e);
    private startRotate();
    private stopRotate();
    private rotate();
    private pan();
    private zoom();
    private raycast(mouse);
}
